version: "3"

services:
  backend:
    image: {{ project_name }}
    restart: always
    env_file: .env
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - media:/app/media
      - static:/app/static
    stdin_open: true
    environment:
      DJANGO_CONFIGURATION: STAGING

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata/
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      PGDATA: /var/lib/postgresql/data/pgdata/

volumes:
  pgdata:
  media:
  static:
